### ISSUE TITLE
[Feature Request] Allow setting a different HttpClient as the client to use

### ISSUE THREAD

**Issue by MattDahEpic** [hoss-green/Tus.Net.Client#3]
As the only C# tus client listed on the tus community implementations page that uses HttpClient as the backing HTTP stack, this library is well-positioned to be the best library for use in integration testing scenarios for ASP.NET applications.

ASP.NET integration tests are primarily performed through an HttpClient that is provided when launching the application for use in the integration test environment. The application being tested is configured by the testing framework to only listen to requests made through an HttpClient generated by the testing framework. By monkey-patching the framework-generated HttpClient in place of the base class in TusHttpClient, I was able to use this library in an integration test where no other C# tus library worked.

The ideal implementation would be either passing in an HttpClient as an optional parameter on the TusFile or TusClient methods or having TusHttpClient use a static HttpClient for its work which could then be overridden in the setup phase for each integration test.

**Comment by hoss-green** [comment]
Resolved in Version 2.0.0
